### ISSUE TITLE
Setup CI for deployment of packages

### ISSUE THREAD

**Issue by vahiwe** [curaOS/source#120]
### Overview

This project needs a CI that automates the deployment of the packages based on commit messages. Any new change to a specific package should trigger the bump and publish. 

### Tasks

- [ ] Generate NPM Token for Authentication
- [ ] Setup Github Actions for CI
- [ ] Test workflow
- [x] #81 
- [x] #127

**Comment by devey** [comment]
> This project needs a CI that automates the deployment of the packages.

Yes, based on commit messages (see [Semantic Release](https://github.com/semantic-release/semantic-release)), but being this a monorepo I found [Semantic Release Monorepo](https://github.com/pmowrer/semantic-release-monorepo)).

> Any new commit with a change to package.json will publish the packages.

It's actually "any new change to a specific package" should trigger the bump and publish

> The release functionality on GitHub could also be used to trigger the deployment.

At the moment builds are automatically deployed to Vercel, either on `master` or on a pull request.

> An automation token needs to be generated for authentication purposes.

You probably only need an `NPM` token for this, If I'm correct.

----

The goal is also to make good use of new `yarn` functionalities, like the [release flow](https://yarnpkg.com/features/release-workflow), and for that, We should try to upgrade to the latest yarn and make sure it doesn't break anything of what we have already, as it introduces a few major changes.

**Comment by devey** [comment]
@vahiwe being this issue an Epic, could you structure it more like this: https://github.com/curaOS/source/issues/58? With an overview and a list of tasks to get it complete.
