### ISSUE TITLE
Error: Model not found for some designs

### ISSUE THREAD

**Issue by 0x5CE** [curaOS/source#122]
The error 'model not found' appears when trying to generate certain models, for instance: https://cura.run/ml/1w/create

**Comment by devey** [comment]
I think this has to do with the fact that the `ML` category is stored with [Runway hosted models](https://runwayml.com/hosted-models/). I will have to look at what happened in the settings there!

**Comment by achrafismyname** [comment]
This one too https://cura.run/ml/1c/create

**Comment by devey** [comment]
Should be fixed now @achrafismyname
