### ISSUE TITLE
Problem with frontend layout

### ISSUE THREAD

**Issue by achrafismyname** [curaOS/source#177]
When we change the project in the frontend, there is a 1 second where the user looks connected to a different project and the theme mode is wrong. This is not good for the user experience and should be fixed.

https://user-images.githubusercontent.com/54310457/144842229-eb52372a-91db-4895-85b5-cdaa4f2edf69.mp4

.

**Comment by AshenI99** [comment]
I just checked this. When we change projects, previous account name is showing until everything gets loaded. But different project names are not appearing inside another projects. 

Hi @achrafismyname Could you tell me this error is still happening for you?

**Comment by achrafismyname** [comment]
Hi @AshenI99, yeah it still happens sometimes as you described
