### ISSUE TITLE
Small design tweaks

### ISSUE THREAD

**Issue by achrafismyname** [curaOS/source#188]
## 1
keep the container width the same in the header and menu
![image](https://user-images.githubusercontent.com/54310457/146631402-0ed27c2c-0448-4035-9fd0-013902c6ab11.png)

## 2
keep this distance the same
![image](https://user-images.githubusercontent.com/54310457/146631454-da6ff3b6-cfe8-4a0e-b4a9-8e7ad304b634.png)

## 3 
Use this logo instead
you can export it from here: https://www.figma.com/file/ZEDDdXRTJxKZH5j5OvGOn4/CURA.RUN?node-id=0%3A1
![image](https://user-images.githubusercontent.com/54310457/146725869-3e2ec343-1a6c-49e8-ada8-c548a034c062.png)

## 4 
Update website favicon to be the same as logo

**Comment by AshenI99** [comment]
## 5

Button texts are not vertically aligned.

<img width="313" alt="Screenshot 2021-12-21 at 19 02 11" src="https://user-images.githubusercontent.com/73756207/147080673-9b76b67a-6cbb-462e-97d6-af41a5bf3d5b.png">


## 6

Slider buttons are overlapping on some mobiles.

<img alt="IMG_9308" src="https://user-images.githubusercontent.com/73756207/147080939-a0df808b-fdf8-4192-b1ad-b3b7cd6c4c0b.PNG" width="400">

**Comment by achrafismyname** [comment]
## 7
The height of the upper bar could be smaller, I still see it very large, if it is possible to shorten it.
![image](https://user-images.githubusercontent.com/54310457/147473439-2b8a8dde-a905-43ad-9103-2d2981aaac4b.png)

## 8
Color of this icons shouldn't change on hover
![image](https://user-images.githubusercontent.com/54310457/147473390-944eb50e-3a59-4ca1-932a-c4181fe315fc.png)

**Comment by achrafismyname** [comment]
## 9
Use this icon for the slider buttons. You can find it here https://www.figma.com/file/ZEDDdXRTJxKZH5j5OvGOn4/CURA.RUN?node-id=0%3A1
![image](https://user-images.githubusercontent.com/54310457/147474057-ec651731-134c-469b-9883-c6cb008d6bc2.png)
