### ISSUE TITLE
Getting undefined error for contractAddress

### ISSUE THREAD

**Issue by AshenI99** [curaOS/source#200]
### Problem

Getting undefined error for `contractAddress` after login.
<img width="600" alt="Screenshot 2021-12-29 at 18 55 51" src="https://user-images.githubusercontent.com/73756207/147667199-5a3071a4-18a1-40f0-b64b-b478e01a4cba.png">

**Comment by achrafismyname** [comment]
Can you provide more info about the conditions which led to this issue

**Comment by achrafismyname** [comment]
I think this is the same issue right? 
https://cura.run/cc/sqgl/explore/art-blocks-58826625

**Comment by AshenI99** [comment]
> I think this is the same issue right?
> https://cura.run/cc/sqgl/explore/art-blocks-58826625

Yeah. It is. We can see the error screen in localhost. 
Just after the login will get this error
